### ISSUE TITLE
option to specify tsconfig

### ISSUE THREAD

**Issue by L2jLiga** [mrazauskas/tsd-lite#91]
currently tsd-lite looking only for tsconfig.json, it would be nice to have option to specify tsconfig file name

**Comment by mrazauskas** [comment]
Could you tell more about your use case, please?

I am wondering if it would make sense to allow passing compiler options? It could be read from any file, or created programmatically:

```ts
import {getTestResult, resolveCompilerOptions } from "tsd-lite";

const configPath = "/path/to/tsconfig.tsd.json";
const testFilePath = "/path/to/testFile.test.ts";

const compilerOptions = resolveCompilerOptions(configPath);

const { assertionsCount, tsdResults } = getTestResult(testFilePath, compilerOptions);

// do something with results
```

For me it seems reasonable to keep the logic of compiler options resolution separate from test file processing. Would it work for your use case?

**Comment by L2jLiga** [comment]
Hi @mrazauskas,

sorry for long delay, yeah, I think it will be enough

My use case is monorepo, I have package with APIs which are used both in FE and BE parts, this package has `composite: true` set in `tsconfig.json` which lead to errors during the tests

**Comment by mrazauskas** [comment]
Just an idea. `tsd-lite` is used to test types of Jest. That’s huge monorepo with `composite: true` in the root `tsconfig.json`. That was causing problems too, so each `__typetests__` directory now includes a `tsconfig.josn`, which extends the root config, but has `composite: false`. See for example: https://github.com/facebook/jest/tree/main/packages/jest-worker/__typetests__

`tsd-lite` is looking for a `tsconfig.josn` closes to actual test file. In this case the one in `__typetests__` directory will be used. By the way, it is also a good idea to add `"types": []` for type tests.

Did you try to go this way? Seemed to me that this solution is very flexible and declarative. Are there any limitations I do not see?

**Comment by L2jLiga** [comment]
Yeah, just checked, seems to be fine for my usecase, thank you for your suggestion!
